# Generated by Django 4.2.2 on 2023-06-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sasg',
        ),
    ]
